Erm 2612, Add support for content type property on Agreements
folio-org/ui-agreements pull request #1196
Opened 2023-03-01 11:21 UTC by MonireRasouli

2023-03-02 09:44 UTC, CalamityC commented on src/components/AgreementSections/ContentTypesFieldArray/ContentTypesFieldArray.js
> +          key={act + index}
I'd prefer template literals here (like eg. in line 98) 
```suggestion
          key={`${act}${index}`}
```

2023-03-02 09:52 UTC, EthanFreestone requested changes
Looks good, can we try to make sure all test refdata though goes to the jest helper file and is then parsed out from there for tests.


We're trying to push towards consistent testing objects, and refdata is the only one we're actually doing right now, so I don't want that to slip

2023-03-02 09:54 UTC, EthanFreestone commented
Ah, in addition, that code smell is pointing at a place where you create a key via concatentation. Please instead create a string like
```
 key={${act?.value}[${index}]}
``` or something. (I don't know the shape of act, if it's already a string then that's fine, but if it's an object it shouldn't be going into the key as is.

2023-03-02 12:27 UTC, CalamityC commented on src/components/AgreementSections/ContentTypesFieldArray/ContentTypesFieldArray.js
> +          key={act + index}
rather use Ethans suggestion as`act` is an object, isn't it?

2023-03-02 15:08 UTC, CalamityC approved these changes

2023-03-02 15:08 UTC, CalamityC commented on src/components/AgreementSections/ContentTypesFieldArray/ContentTypesFieldArray.js
> +          key={`${act?.contentType?.id}`}
That's fine I think. Although you're using here the refdata id (the contentType object is the refdata object), you could also use `act.id` which is the specific id of the agreementContentType object. But as we're not allowing to set a refdata value twice on an agreement, your `key` is also unique per agreement, so all should be good.

2023-03-13 15:47 UTC, EthanFreestone approved these changes

2023-03-14 10:55 UTC, merged