ERM-1236: Incorrect message on PCI screen
folio-org/ui-agreements pull request #700
Opened 2020-12-18 11:49 UTC by peterboehm

2020-12-18 17:31 UTC, aditya-matukumalli requested changes

2020-12-18 17:31 UTC, aditya-matukumalli commented on src/components/CoverageFieldArray/CoverageFieldArray.js
> +    isEmptyCoverageMessage: PropTypes.string,
Can you change the proptype to `isEmptyCoverageId` instead? as its an id but not the actual message

2020-12-18 17:31 UTC, aditya-matukumalli commented on translations/ui-agreements/en_US.json
> +    "emptyAccordion.lineCoverageEresource": "No coverage for this e-resource",
As its a new translation, we dont have to add it to the `en_US` file

2020-12-21 16:26 UTC, peterboehm commented
Thanks, I made the requested changes

2020-12-21 16:31 UTC, aditya-matukumalli approved these changes

2020-12-21 16:31 UTC, merged