ERM-1467 Added tests for AgreementCreateRoute
folio-org/ui-agreements pull request #912
Opened 2021-10-20 07:47 UTC by MonireRasouli

*Added data-testid="agreements" to AgreementForm component
*Added testResources file
*Added tests for AgreementCreateRoute

2021-10-31 19:23 UTC, MonireRasouli commented on src/components/views/AgreementForm.js
> +        <div data-testid="agreements">
I don't use it anywhere, it should be removed.

2021-11-01 14:51 UTC, aditya-matukumalli requested changes

2021-11-01 14:51 UTC, aditya-matukumalli commented on src/routes/AgreementCreateRoute/AgreementCreateRoute.js
> +  /* istanbul ignore next */
Lets pass a button down and trigger the onSubmit to cover this callback

2021-11-04 02:16 UTC, aditya-matukumalli requested changes

2021-11-04 02:16 UTC, aditya-matukumalli commented on src/routes/AgreementCreateRoute/AgreementCreateRoute.test.js
> +      expect(getByText('stripes-smart-components.permissionError')).toBeInTheDocument();
Please make the changes here once the translation is added to translationProperties file

2021-11-05 22:09 UTC, aditya-matukumalli approved these changes

2021-11-05 22:24 UTC, merged